baseURL = "https://decodetech.eu"
title = "DecodeTech"
copyright = "© DecodeTech - 2022"
paginate = 2
summaryLength = 15
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "my-hugo-theme-chunky-poster"
ignoreErrors = ["error-remote-getjson"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 0
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 11
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 0

[taxonomies]
category = "category"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Antoine-Alexandre"
  description = "Uncovering how technologies are changing societies."
  homepageImage = "/images/homepage-image.png"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    linkedin = "https://www.linkedin.com/company/decodetech"
    twitter = "https://twitter.com/decodetech_eu"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://cdn.commento.io/js/commento.js"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
